export { default as Home } from './home/index.jsx';
export { default as Register } from "./register/index.jsx";
export { default as RecoverPassword } from "./recoverPassword/index.jsx";
export { default as ChangePassword } from "./changePassword/index.jsx";
export { default as Admin } from "./admin/admin.jsx";
export { default as Perfil } from "./perfil/perfil.jsx"
export { default as Auction } from "./auctions/auction.jsx"
export { default as AuctionForm } from "./auctions/create/AuctionForm.jsx"
export { default as AuctionDetail } from "./auctions/detail/auctionDetail.jsx"
export { default as NotFound } from "./notfound/NotFound.jsx"